# orbs:
#   node: circleci/node@4.0.0

# version: 2.1

# workflows:
#   matrix-tests:
#     jobs:
#       - node/test

version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12

        steps:
            - checkout
            - run: yarn
            - run: yarn tsc
            - run: yarn test